### ISSUE TITLE
ZSH in compiling

### ISSUE THREAD

**Issue by carterartist** [ErikLevin/calibre_rpggeek_plugin#1]
I noticed the errors: 

zsh: no such file or directory: .venv/Scripts/activate
zsh: command not found: pip

when compiling... 

I then di the .psh file and tried the test and got:

zsh: command not found: calibre-customize
zsh: command not found: calibre-debug

not sure what to do, can't get this to work.

below is the full terminal

`Last login: Sun Nov 12 15:48:50 on ttys001
seancarter@Seans-iMac ~ % git clone https://github.com/kovidgoyal/calibre.git

git clone https://github.com/ErikLevin/calibre_rpggeek_plugin.git
cd calibre_rpggeek_plugin
python -m venv .venv
.venv/Scripts/activate
pip install -r requirements.txt
Cloning into 'calibre'...
remote: Enumerating objects: 388347, done.
remote: Counting objects: 100% (22866/22866), done.
remote: Compressing objects: 100% (963/963), done.
remote: Total 388347 (delta 22081), reused 22456 (delta 21903), pack-reused 365481
Receiving objects: 100% (388347/388347), 290.92 MiB | 38.04 MiB/s, done.
Resolving deltas: 100% (311775/311775), done.
Updating files: 100% (5951/5951), done.
Cloning into 'calibre_rpggeek_plugin'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 24 (delta 7), reused 21 (delta 4), pack-reused 0
Unpacking objects: 100% (24/24), done.
zsh: no such file or directory: .venv/Scripts/activate
zsh: command not found: pip
seancarter@Seans-iMac calibre_rpggeek_plugin % calibre-customize -b .
calibre-debug -e test.py
zsh: command not found: calibre-customize
zsh: command not found: calibre-debug
seancarter@Seans-iMac calibre_rpggeek_plugin % 
`

**Comment by ErikLevin** [comment]
Hi, do you have python installed? 

You may also be interested in knowing that this plugin isn't feature complete and I'm not currently working on it. (But of course you are more than welcome to check it out anyway. It kinda works, although limited)

**Comment by carterartist** [comment]
I would just like to see how it works...

and I have the 

/Users/seancarter/calibre/src
in the Calibre.pth file in the "site-packages".

When I try the test.py file I get:
`Last login: Mon Nov 13 20:04:31 on ttys002
cd '/Users/seancarter/calibre_rpggeek_plugin/' && '/usr/local/bin/python3'  '/Users/seancarter/calibre_rpggeek_plugin/rpggeek_source.py'  && echo Exit status: $? && exit 1
seancarter@Seans-iMac ~ % cd '/Users/seancarter/calibre_rpggeek_plugin/' && '/usr/local/bin/python3'  '/Users/seancarter/calibre_rpggeek_plugin/rpggeek_source.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/seancarter/calibre_rpggeek_plugin/rpggeek_source.py", line 10, in <module>
    from calibre.ebooks.metadata.book.base import Metadata
ModuleNotFoundError: No module named 'calibre'
seancarter@Seans-iMac calibre_rpggeek_plugin % `

**Comment by ErikLevin** [comment]
Are you running

```
calibre-customize -b .
calibre-debug -e test.py
```
?

**Comment by carterartist** [comment]
When I do that:

Last login: Mon Nov 13 20:04:40 on ttys003
seancarter@Seans-iMac ~ % calibre-customize -b .
calibre-debug -e test.py
zsh: command not found: calibre-customize
zsh: command not found: calibre-debug
seancarter@Seans-iMac ~ %

**Comment by ErikLevin** [comment]
So Calibre is obviously not on your Path.
Feels like we're having the [XY problem](https://en.wikipedia.org/wiki/XY_problem).
Could you please clarify what exactly you hope to achieve here. "I would just like to see how it works..." you said. See how what works and to what end?

I don't want to sound rude or dismissive. But please understand that I'm just a random person on Github and I don't have the spare time to help with general computer usage, Python, or Calibre plugin development questions. I can try to answer your questions about this specific repo or discuss improvements etc., and PRs and/or forks are more than welcome.

**Comment by carterartist** [comment]
I was hoping I could use it to access RPGGeek for my pdfs for D&D...

But I guess I'll have to figure it out on my own... ty
